### ISSUE TITLE
[bug] ImportError: cannot import name 'OrderedDict' when debugging ROS2 in Jetson Container

### ISSUE THREAD

**Issue by polyhobbyist** [ms-iot/vscode-ros#620]
(Please add appropriate labels)
- [ ] Windows: (Version)
- [X] Linux:  (Dist/Version)
- [ ] ROS 1: Dist
- [X] ROS 2: Foxy

\<Version of the plugin\> 0.7.0

## Repro steps
Create a dockerfile which derives from dustynv/ros:foxy-slam-l4t-r32.5.0, with a docker-compose which instantiates it like:

``` yaml
version: '3.4'

services:
  mulews:
    image: ws
    network_mode: "host"
    volumes:
      - ~/ws:/ws
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /dev/i2c-1:/dev/i2c-1
      - /dev/bus/usb:/dev/bus/usb
      - /dev/ttyTHS1:/dev/ttyTHS1
    build:
      context: .
      dockerfile: ./Dockerfile
    command: /bin/sh -c "while sleep 1000; do :; done"
```
# expected behavior
Attempt to debug a ROS2 launch file.

``` bash
Traceback (most recent call last):
  File "/root/.vscode-server/extensions/ms-iot.vscode-ros-0.6.9/assets/scripts/ros2_launch_dumper.py", line 16, in <module>
    from typing import OrderedDict
ImportError: cannot import name 'OrderedDict'
```

the nvidia containers have an older version of python, which isn't typical:
```bash
python --version
Python 3.6.9
```

Therefore OrderedDict is not in the typing module. It is in the collections module.

To support Jetson container deployments, suggest using a switch to support both?
